import {IssueMessage} from "./issue-message";
import {FileAttachment} from "./file-attachment";
import {IssueAction} from "./issue-action";
import {IssueHistory} from "./issue-history";
import {IssueCheck} from "./issue-check";
export class Issue {
  id: number = 0;
  status: string = '';
  project: string = '';
  department: string = '';
  started_by: string = '';
  started_date: any = 0;
  issue_type: string = '';
  name: string = '';
  details: string = '';
  assigned_to: string = '';
  start_date: any = 0;
  due_date: any = 0;
  messages: IssueMessage[] = [];
  history: IssueHistory[] = [];
  file_attachments: FileAttachment[] = [];
  priority: string = '';
  doc_number: string = '';
  responsible: string = '';
  overtime: string = '';
  period: string = '';
  child_issues: Issue[] = [];
  combined_issues: Issue[] = [];
  action: string = '';
  actions: IssueAction[] = [];
  last_update: number = 0;
  closing_status: string = '';
  parent_id: number = 0;
  delivered_date: any = 0;
  issue_comment: string = '';
  sfi_code: string = '';
  first_send_date: number = 0;
  first_local_approval_date: number = 0;
  revision: string = '';
  revision_files: FileAttachment[] = [];
  cloud_files: FileAttachment[] = [];
  archive_revision_files: FileAttachment[] = [];
  labor: number = 0;
  contract_due_date: number = 0;
  checks: IssueCheck[] = [];
  ready: string = '000';
  readyM: boolean = false;
  readyD: boolean = false;
  readyN: boolean = false;
  for_revision = '-';
  subscribers: string[] = [];
  plan_hours: number = 0;
  plan_hours_locked: number = 0;
  assistant = '';
  reason_of_changes = '';
  modification_of_existing = 0;
  modification_description = '';
  recommended_response_date: Date;
  started_date_as_date: Date;
}
