export class User {
  id: number = 0;
  login: string = '';
  password: string = '';
  name: string = '';
  surname: string = '';
  profession: string = '';
  birthday: number = 0;
  email: string = '';
  phone: string = '';
  tcid: number = 0;
  avatar: string = '';
  token: string = '';
  groups: string[] = [];
  permissions: string[] = [];
  userName: string = '';
  userNameEn: string = '';
  visibility: string = '';
  gender: string = '';
  department: string = '';
  avatar_full: string = '';
  rocket_login: string = '';
  visible_projects: string[] = [];
  visible_pages: string[] = [];
  shared_access: string = '';
  props: any = Object();
}
